services:
  app:
    build: .
    volumes:
      - ./:/root/take_home_project
    command: flask run --host 0.0.0.0 --port 8888
    ports:
      - "8888:8888"
    env_file:
      - ./local.env
  postgres:
    image: postgres:15.2
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./local.env
    ports:
      - "5432:5432"
